/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_monitoring_runtime_instrumentation_TimeHolder */

#ifndef _Included_com_google_monitoring_runtime_instrumentation_TimeHolder
#define _Included_com_google_monitoring_runtime_instrumentation_TimeHolder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_monitoring_runtime_instrumentation_TimeHolder
 * Method:    clearTree2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_monitoring_runtime_instrumentation_TimeHolder_clearTree2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
