/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class instrumenter_LayerCallback */

#ifndef _Included_instrumenter_LayerCallback
#define _Included_instrumenter_LayerCallback
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     instrumenter_LayerCallback
 * Method:    callbackLayerInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_instrumenter_LayerCallback_callbackLayerInfo
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
