name: build master
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: set java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      script: true
